apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: todo-application
  template:
    metadata:
      labels:
        app: todo-application
    spec:
      containers:
      - name: todo-container
        image: techiepawan/todo-app:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-application
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8000  # Port in container
  type: LoadBalancer  # Change to LoadBalancer for external access